<?php

function responsive_images_filter_info() {
  $filters = array();
  $filters['responsive_image_filter'] = array(
    'title' => t('Responsive Image Filter'),
    'description' => t('Substitutes [image:URL|,class_name] with responsive image.'),
    'process callback' => '_responsive_images_filter_process',
    'settings callback' => '_responsive_images_filter_settings',
    'default settings' => array(
      'responsive_image_filter_image-style' => false,
    ),
    'weight' => -1,
  );
  return $filters;
}
function _responsive_images_filter_settings($form, &$form_state, $filter, $format, $defaults, $filters) {

  $styles = array();
  foreach( image_styles() as $style ){
    $styles[$style['name']] = $style['name'];
  }


  $settings['responsive_image_filter_image-style'] = array(
    '#type' => 'select',
    '#title' => t('Image Style'),
    '#default_value' => isset($filter->settings['responsive_image_filter_image-style']) ? $filter->settings['responsive_image_filter_image-style'] : false,
    '#options' => $styles,
  );

  return $settings;
}
function _responsive_images_filter_process($text, $filter, $format, $langcode, $cache, $cache_id) {

  $uri = 'public://';
  $public_path= str_replace($GLOBALS['base_url'], '', file_create_url($uri));

  if (preg_match_all("/\\[image:\\s*([^,]+)(,(.+))?\\]/isU", $text, $matches_code)) {

    foreach($matches_code[0] as $ci => $code){

      $styled_uri = substr(strrchr($matches_code[1][$ci],'/'), 1);
      $uri = "public://".str_replace(strstr($styled_uri,'?'),'',$styled_uri);

      $image = array(
        'uri' => $uri,
        'path' => $uri,
        'style_name' => $filter->settings['responsive_image_filter_image-style'],
        'classes' => (isset($matches_code[3][$ci])) ? $matches_code[3][$ci] : null
      );

      $replacement = responsive_images_image_render($image);
      $text = str_replace($code, $replacement, $text);
    }
  }

  return $text;
}


function responsive_images_theme_registry_alter(&$theme_registry) {
  foreach ($theme_registry as $key => $info) {
    if ($key == 'image_style') {
      $theme_registry[$key]['function'] = 'responsive_images_image_style';
    }
  }
}
function responsive_images_get_responsive_styles(){

  $responsive_styles = array(
    'triggers' => array(),
    'groups' => array()
  );

  foreach(image_styles() as $key => $style){

    if( preg_match("/(rs_[a-z-\\s]+)_?(min_)?([0-9pxw]+)?/u", $style['label'], $matches) !== 0) {

      $rstyle = array();
      $style_group = $matches[1];

      //check to see if style_group exists
      if(!isset($responsive_styles['groups'][$style_group])){
        $responsive_styles['groups'][$style_group] = array();
      }

      if(isset($matches[3]) && strlen($matches[3]) > 0){

        //group
        $rstyle = array(
          'float' => floatval($matches[3]),
          'width' => (strstr($matches[3],"w") !== false) ? $matches[3] : false,
          'machine_value' => $style['name']
        );
        //add
        $responsive_styles['groups'][$style_group][] = $rstyle;

      } else {
        //tigger style
        $responsive_styles['triggers'][] = $style_group;
      }
    }
  }

  //make triggers unique
  $responsive_styles['triggers'] = array_unique($responsive_styles['triggers']);

  //sort groups by min
  foreach($responsive_styles['groups'] as $key => $group){
    $sort = array();
    foreach($group as $item){
      $sort[] = $item['float'];
    }

    array_multisort( $sort, SORT_ASC, $responsive_styles['groups'][$key] );
  }

  return $responsive_styles;

}

function responsive_images_get_responsive_group(&$styles, $style_name){

  if(($key=array_search($style_name,$styles['triggers'])) !== false){
    return $styles['triggers'][$key];
  }

  return false;
}

function responsive_images_image_style(&$variables) {
  $styles = responsive_images_get_responsive_styles();

  if( ($rs_group = responsive_images_get_responsive_group($styles, $variables['style_name']) ) !== false ){
    $variables['rs_group'] = $styles['groups'][$rs_group];
    return responsive_images_image_render($variables);
  }

  // Determine the dimensions of the styled image.
  $dimensions = array(
    'width' => $variables['width'],
    'height' => $variables['height'],
  );
  // Determine the URL for the styled image.
  $variables['path'] = image_style_url($variables['style_name'], $variables['path']);
  return theme('image', $variables);
}
function responsive_images_image_render($image){

  if(!isset($image['rs_group'])){
    $styles = responsive_images_get_responsive_styles();
    $rs_group = responsive_images_get_responsive_group($styles, $image['style_name']);
    if($rs_group === false){
      return 'Could not find responsive group style. Error.';
    }
    $image['rs_group'] = $styles['groups'][$rs_group];
  }

  drupal_add_js(drupal_get_path('module', 'responsive_images').'/responsive-image.min.js');

  $output = '<div class="responsive-image '.$image['style_name'].((isset($image['parent-classes'])) ? ' '.$image['parent-classes'] : '').'">'."\n";

  $srcset="";
  foreach($image['rs_group'] as $group){
    if( $group['width'] == false ){
      if(!isset($image['width'])){
        $i = image_load($image['path']);
        $dimensions = array('width'=>$i->info['width'],'height'=>$i->info['height']);
      } else {
        $dimensions = array('width'=>$image['width'],'height'=>$image['height']);
      }
      image_style_transform_dimensions($group['machine_value'], $dimensions);

      $group['width'] = $dimensions['width'].'w';
    }
    $srcset .= image_style_url($group['machine_value'],$image['path']).' '.$group['width'].',';
  }
  $srcset = substr($srcset,0,-1);

  $output .= '<img srcset="'.$srcset.'" src="'.image_style_url($image['rs_group'][0]['machine_value'], $image['path']).'" alt="'.((isset($image['title'])) ? $image['title'] : '').'" '.((isset($image['classes'])) ? 'class="'.$image['classes'].'"' : '').' sizes="100vw" />'."\n";

  $output .= "</div>\n";

  $output = str_replace($GLOBALS['base_url'],'',$output);

  return $output;
}
