<?php

function responsive_images_preprocess_html(&$variables) {
  responsive_images_add_js();
}

function responsive_images_filter_info() {
  $filters = array();
  $filters['responsive_image_filter'] = array(
    'title' => t('Responsive Image Filter'),
    'description' => t('Substitutes [image:URL|,class_name] with responsive image.'),
    'process callback' => '_responsive_images_filter_process',
    'settings callback' => '_responsive_images_filter_settings',
    'default settings' => array(
      'responsive_image_filter_image-style' => false,
    ),
    'weight' => -1,
  );
  return $filters;
}
function _responsive_images_filter_settings($form, &$form_state, $filter, $format, $defaults, $filters) {

  $styles = array();
  foreach( image_styles() as $style ){
    $styles[$style['name']] = $style['name'];
  }


  $settings['responsive_image_filter_image-style'] = array(
    '#type' => 'select',
    '#title' => t('Image Style'),
    '#default_value' => isset($filter->settings['responsive_image_filter_image-style']) ? $filter->settings['responsive_image_filter_image-style'] : false,
    '#options' => $styles,
  );

  return $settings;
}
function _responsive_images_filter_process($text, $filter, $format, $langcode, $cache, $cache_id) {

  $uri = 'public://';

  //decode text for url encodings
  $text = urldecode($text);

  //find images in public folder and overwrite
  if( preg_match_all('/<img[\\w\\W]+?src="\/sites\/default\/files\/styles\/[\\w]+\/public\/([\\w\\s-%_?=\\.]+)"[\\w\\W]+?\/>/u', $text, $matches_code) ){

    foreach($matches_code[0] as $ci => $code){

      //get image filename
      $img = $matches_code[1][$ci];

      //remove any parameters
      $img = strstr($img, '?', true);

      $uri = "public://".$img;

      $classes = null;
      if( preg_match('/class="([\\w\\s-_]*)"/u', $code, $matches) ){
        $classes = $matches[1];
      }
      $style = null;
      if( preg_match('/style="(.+)"/u', $code, $matches) ){
        $style = $matches[1];
      }
      $title = null;
      if( preg_match('/alt="([\\w\\s_-]*)"/u', $code, $matches) ){
        $title = $matches[1];
      }

      $image = array(
        'uri' => $uri,
        'path' => $uri,
        'style_name' => $filter->settings['responsive_image_filter_image-style'],
        'classes' => $classes,
        'title' => $title,
      );

      if($style != null){
        $image['style'] = $style;
      }

      $replacement = responsive_images_image_render($image);
      $text = str_replace($code, $replacement, $text);
    }

  }

  //find old image insert items
  if (preg_match_all("/\\[image:\\s*([^,]+)(,(.+))?\\]/isU", $text, $matches_code)) {

    foreach($matches_code[0] as $ci => $code){

      $styled_uri = substr(strrchr($matches_code[1][$ci],'/'), 1);
      $uri = "public://".str_replace(strstr($styled_uri,'?'),'',$styled_uri);

      $image = array(
        'uri' => $uri,
        'path' => $uri,
        'style_name' => $filter->settings['responsive_image_filter_image-style'],
        'classes' => (isset($matches_code[3][$ci])) ? $matches_code[3][$ci] : null
      );

      $replacement = responsive_images_image_render($image);
      $text = str_replace($code, $replacement, $text);
    }
  }

  return $text;
}


function responsive_images_theme_registry_alter(&$theme_registry) {
  foreach ($theme_registry as $key => $info) {
    if ($key == 'image_style') {
      $theme_registry[$key]['function'] = 'responsive_images_image_style';
    }
  }
}
function responsive_images_get_responsive_styles(){

  $responsive_styles = array(
    'triggers' => array(),
    'groups' => array()
  );

  foreach(image_styles() as $key => $style){

    if( preg_match("/(rs_[0-9a-z-\\s]+)_?(min_)?([0-9pxw]+)?/u", $style['label'], $matches) !== 0) {

      $rstyle = array();
      $style_group = $matches[1];

      //check to see if style_group exists
      if(!isset($responsive_styles['groups'][$style_group])){
        $responsive_styles['groups'][$style_group] = array();
      }

      if(isset($matches[3]) && strlen($matches[3]) > 0){

        //group
        $rstyle = array(
          'float' => floatval($matches[3]),
          'width' => (strstr($matches[3],"w") !== false) ? $matches[3] : false,
          'machine_value' => $style['name']
        );
        //add
        $responsive_styles['groups'][$style_group][] = $rstyle;

      } else {
        //tigger style
        $responsive_styles['triggers'][] = $style_group;
      }
    }
  }

  //make triggers unique
  $responsive_styles['triggers'] = array_unique($responsive_styles['triggers']);

  //sort groups by min
  foreach($responsive_styles['groups'] as $key => $group){
    $sort = array();
    foreach($group as $item){
      $sort[] = $item['float'];
    }

    array_multisort( $sort, SORT_ASC, $responsive_styles['groups'][$key] );
  }

  return $responsive_styles;

}

function responsive_images_get_responsive_group(&$styles, $style_name){

  if(($key=array_search($style_name,$styles['triggers'])) !== false){
    return $styles['triggers'][$key];
  }

  return false;
}

function responsive_images_image_style(&$variables) {
  $styles = responsive_images_get_responsive_styles();

  if( ($rs_group = responsive_images_get_responsive_group($styles, $variables['style_name']) ) !== false ){
    $variables['rs_group'] = $styles['groups'][$rs_group];
    drupal_add_css(drupal_get_path('module', 'responsive_images').'/css/responsive_images.css');
    return responsive_images_image_render($variables);
  }

  // Determine the dimensions of the styled image.
  $dimensions = array(
    'width' => $variables['width'],
    'height' => $variables['height'],
  );
  image_style_transform_dimensions($variables['style_name'], $dimensions);

  $variables['width'] = $dimensions['width'];
  $variables['height'] = $dimensions['height'];

  // Determine the URL for the styled image.
  $variables['path'] = image_style_url($variables['style_name'], $variables['path']);
  return theme('image', $variables);
}

function responsive_images_add_js(){
  //add img tag scripts
  drupal_add_js(drupal_get_path('module', 'responsive_images').'/rspolly.js');
  drupal_add_js(drupal_get_path('module', 'responsive_images').'/lazysizes.min.js',array('async' => true));
  drupal_add_js(drupal_get_path('module', 'responsive_images').'/respimage.min.js',array('async' => true));
  //add background scripts
  drupal_add_js(drupal_get_path('module', 'responsive_images').'/intersection-observer.js',array('async' => true));
  drupal_add_js(drupal_get_path('module', 'responsive_images').'/lazybg.js',array('async' => true));
}

function responsive_images_image_render_svg($image){
  $url = file_create_url($image['uri']);
  return "<figure class='responsive-image svg'>\n<img src='$url' alt='${image['alt']}' />\n</figure>\n";
}

function responsive_images_image_render_bg($image, $single=true){

  if($single == true){
    $image['class'] = uniqid('rsbg');
  }

  //set lazyload if not already set
  if(!isset($image['lazyload'])){
    $image['lazyload'] = true;
  }

  if(!isset($image['classes'])){
    $image['classes'] = '';
  }

  $image['style'] = (isset($image['style'])) ? $image['style'] : '';
  $image['classes'] .= ($image['lazyload'] == true) ? ' lazybg' : '';

  $output = '<figure class="first responsive-image-bg responsive-image '.$image['style_name'].$image['classes'].' '.$image['class'].'"'.$image['style'].'></figure>'."\n";

  if($single == true){
    $output .= "<style>\n";
    $output .= responsive_images_image_render_style($image, $image['lazyload']);
    $output .= "</style>\n";

    if( $image['use_relative_path'] == true ){
      $output = str_replace($GLOBALS['base_url'],'',$output);
    }

  }

  return $output;
}
function responsive_images_image_group_render_bg($images){
  $output = "<div class='responsive-background images'>\n";

  for($i=0; $i< count($images); $i++){
    $images[$i]['class'] .= ' '.uniqid('rsbg');
    $output .= responsive_images_image_render_bg($images[$i], false);
  }

  $output .= "</div>\n";

  $output .= "<style>\n";
  for($i=0; $i < count($images); $i++){
    $output .= responsive_images_image_render_style($images[$i]);
  }

  $output .= "</style>\n";

  $output = str_replace($GLOBALS['base_url'],'',$output);
  return $output;
}
function responsive_images_image_render_style($image, $lazyload=false){
  if(!isset($image['rs_group'])){
    $styles = responsive_images_get_responsive_styles();
    $rs_group = responsive_images_get_responsive_group($styles, $image['style_name']);
    if($rs_group === false){
      return 'Could not find responsive group style. Error.';
    }
    $image['rs_group'] = $styles['groups'][$rs_group];
  }


  $output = "";

  $sort = array();
  foreach($image['rs_group'] as $group){
    $sort[] = $group['float'];
  }

  array_multisort( $sort, SORT_ASC, $image['rs_group'] );

  if($lazyload == true){
    $image['class'] .= '.visible';
  }

  foreach($image['rs_group'] as $i => $group){
    $output .= "\t@media only screen and (min-width: ".($group['float']/1)."px){ .".$image['class']." { background-image: url(".image_style_url($group['machine_value'],$image['path'])."); }}\n";

    $output .= "\t@media only screen and (-webkit-min-device-pixel-ratio: 2) , (min-resolution: 192dpi) and (min-width: ".($group['float'] / 2)."px){ .".$image['class']." { background-image: url(".image_style_url($group['machine_value'],$image['path'])."); }}\n";
  }

  return $output;
}

function responsive_images_findGroup($min_size,$groups){
  foreach($groups as $group){
    if($group['float'] >= $min_size){
      return $group;
    }
  }
  return false;
}

/*
 * $image_array item =>
 * ['query'=>'(min-width: 36em)','type' => 'source/img', 'img' => '<img src="" />']
 * returns <picture> element
 */
function responsive_images_picture_render($image_array) {

  $el = 'picture';
  $class = 'rs_picture';

  //check to see if any of the images are set to render as a background
  foreach ($image_array as $source) {
    if ( isset($source['img']['render_as_bg']) && $source['img']['render_as_bg'] == true ) {
      $el = 'div';
      break;
    }
  }

  foreach ($image_array as $source) {
    if ($el == 'div') {
      $output .= _responsive_images_render_picture_bg($source)."\n";
    } else {
      $output .= _responsive_images_render_picture_source($source)."\n";
    }
  }

  return "<$el class='$class'>\n$output</$el>";
}

function _responsive_images_render_picture_bg($source) {
  $type = (isset($source['type'])) ? $source['type'] : 'source';

  if ($type == 'img') {
    return '';
  }

  $id = uniqid('rspicture');

  $style = '';
  if(isset($source['query'])) {
    $style = "<style>.$id { display: none; } @media ".$source['query']." { .$id { display: block; } }</style>\n";
  }

  return "$style<div class='$id rs_picture_source'>\n".responsive_images_image_render_bg($source['img'])."\n</div>";
}

function _responsive_images_render_picture_source($source) {
  //set defaults
  $type = (isset($source['type'])) ? $source['type'] : 'source';

  $media = (isset($source['query'])) ? ' media="'.$source['query'].'"' : '';

  $img = responsive_image_render_img($source['img']);

  $img = str_replace('<img','<'.$type.$media,$img);

  return $img;
}

function responsive_images_image_render($image){

  //set use relative path if not set
  if(!isset($image['use_relative_path'])){
    $image['use_relative_path'] = true;
  }

  //make sure classes is set
  if(!isset($image['classes'])){
    $image['classes'] = '';
  }

  $image['style'] = (isset($image['style'])) ? ' style="'.$image['style'].'"' : '';

  //set lazyload if not already set
  if(!isset($image['lazyload'])){
    $image['lazyload'] = true;
  }

  //set path if not set
  if(!isset($image['path']) && isset($image['uri'])){
    $image['path'] = $image['uri'];
  }

  if(isset($image['filemime']) && $image['filemime'] == 'image/svg+xml'){
    return responsive_images_image_render_svg($image);
  }

  if(isset($image['render_as_bg']) && $image['render_as_bg'] == true){
    return responsive_images_image_render_bg($image);
  }


  $output = '<div class="responsive-image '.$image['style_name'].((isset($image['parent-classes'])) ? ' '.$image['parent-classes'] : '').'"'.$image['style'].'>'."\n";

  $output .= responsive_image_render_img($image)."\n";

  $output .= "</div>\n";

  if( $image['use_relative_path'] == true ){
    $output = str_replace($GLOBALS['base_url'],'',$output);
  }

  return $output;
}

function responsive_image_render_img($image){

  //set use relative path if not set
  if(!isset($image['use_relative_path'])){
    $image['use_relative_path'] = true;
  }

  if(!isset($image['classes'])){
    $image['classes'] = '';
  }

  $image['style'] = (isset($image['style'])) ? ' style="'.$image['style'].'"' : '';

  //set lazyload if not already set
  if(!isset($image['lazyload'])){
    $image['lazyload'] = true;
  }

  //set path if not set
  if(!isset($image['path']) && isset($image['uri'])){
    $image['path'] = $image['uri'];
  }

  $cachebuster = "";
  if(isset($image['cachebuster'])){
    $cachebuster = "&v=".$image['cachebuster'];
  }

  if(!isset($image['rs_group'])){
    $styles = responsive_images_get_responsive_styles();
    $rs_group = responsive_images_get_responsive_group($styles, $image['style_name']);
    if($rs_group === false){
      return 'Could not find responsive group style. Error.';
    }
    $image['rs_group'] = $styles['groups'][$rs_group];
  }

  $srcset="";
  foreach($image['rs_group'] as $group){
    if( $group['width'] == false ){
      if(!isset($image['width'])){
        $i = image_load($image['path']);
        $dimensions = array('width'=>$i->info['width'],'height'=>$i->info['height']);
      } else {
        $dimensions = array('width'=>$image['width'],'height'=>$image['height']);
      }
      image_style_transform_dimensions($group['machine_value'], $dimensions);

      $group['width'] = $dimensions['width'].'w';
    }
    $srcset .= image_style_url($group['machine_value'],$image['path']).$cachebuster.' '.$group['width'].',';
  }
  $srcset = substr($srcset,0,-1);

  if($image['lazyload'] == true){
    $image['classes'] .= ' lazyload';
    if(!isset($image['sizes'])){
      $image['sizes'] = 'auto';
    }
  }

  $sizes = (isset($image['sizes'])) ? $image['sizes'] : '100vw';

  $srcv = ($image['lazyload'] == true) ? 'data-src' : 'src';
  $srcsetv = ($image['lazyload'] == true) ? 'data-srcset' : 'srcset';

  if(!isset($image['src_style'])){
    $image['src_style'] = $image['rs_group'][0]['machine_value'];
  }

  $src = image_style_url($image['src_style'], $image['path']).$cachebuster;

  $attributes = (isset($image['attributes'])) ? ' '.$image['attributes'].' ' : '';

  return '<img '.(($image['lazyload'] == true) ? 'srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" ' : '').$srcsetv.'="'.$srcset.'" '.$srcv.'="'.$src.'" alt="'.((isset($image['title'])) ? $image['title'] : '').'" '.((isset($image['classes'])) ? 'class="'.$image['classes'].'"' : '').' sizes="'.$sizes.'"'.$attributes.' />';


}
